#ifndef RHD2000EVALBOARDIMPEDANCETESTER_GLOBAL_H
#define RHD2000EVALBOARDIMPEDANCETESTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RHD2000EVALBOARDIMPEDANCETESTER_LIBRARY)
#  define RHD2000EVALBOARDIMPEDANCETESTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RHD2000EVALBOARDIMPEDANCETESTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RHD2000EVALBOARDIMPEDANCETESTER_GLOBAL_H
